name = "JSONStat"
uuid = "49d6b9cb-bec4-42b6-b442-6ff0bc24f19a"
authors = ["lsaenzt <59137624+lsaenzt@users.noreply.github.com>"]
version = "0.1.0"

[deps]
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
